function [hVT_o,halpha_o,hbeta_o,hP_o,hQ_o,hR_o,...
          hHxbody_o,hHybody_o,hHzbody_o...
          ]...
          =h_x_u_state_EKF_sailplane(...
                    ~,~,~,~,...
                    VT_o,alpha_o,beta_o,phi_o,theta_o,psi_o,P_o,Q_o,R_o,...
                    alphab_o,betab_o,...
                    HN0noaa,HE0noaa,HD0noaa)

%%h(x,u)
hVT_o=VT_o;
halpha_o=alpha_o+alphab_o;
hbeta_o=beta_o+betab_o;
hP_o=P_o;
hQ_o=Q_o;
hR_o=R_o;
hHxbody_o=HN0noaa*cos(theta_o)*cos(psi_o)+...
          HE0noaa*cos(theta_o)*sin(psi_o)-...
          HD0noaa*sin(theta_o);
hHybody_o=HN0noaa*(sin(phi_o)*sin(theta_o)*cos(psi_o)-cos(phi_o)*sin(psi_o))+...
          HE0noaa*(sin(phi_o)*sin(theta_o)*sin(psi_o)+cos(phi_o)*cos(psi_o))+...
          HD0noaa*sin(phi_o)*cos(theta_o);
hHzbody_o=HN0noaa*(cos(phi_o)*sin(theta_o)*cos(psi_o)+sin(phi_o)*sin(psi_o))+...
          HE0noaa*(cos(phi_o)*sin(theta_o)*sin(psi_o)-sin(phi_o)*cos(psi_o))+...
          HD0noaa*cos(phi_o)*cos(theta_o);   
      